language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "python setup.py install"

# command to run tests
script:
  - python tests/testLocation.py
  - python tests/testMove.py
  - python tests/testConverter.py
  - python tests/testBoard.py
  - python tests/testStr.py

branches:
  only:
    - master